### ISSUE TITLE
System.InvalidOperationException: Sequence contains no matching element

### ISSUE THREAD

**Issue by billthecatt** [tpill90/epic-lancache-prefill#30]
**Describe the bug**
When I run EpicPrefill  prefill -f I get the error: "System.InvalidOperationException: Sequence contains no matching element"

**Additional Details**
 - Platform you are running EpicPrefill on:  
 
 Debian GNU/Linux 11 
 
 Linux lancache 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux on bare metal
 
 - Discord Username (if you are part of the Lancache Discord Server) : billcat
 - Region : Central US

**Screenshots**
user1@lancache:~/EpicPrefill$ ./update.sh
 Checking for latest version
 Found latest version :  1.1.1
 Downloading...
EpicPrefill-1.1.1-linux-x64.zip                      100%[======================================================================================================================>]  12.67M  --.-KB/s    in 0.1s
 Unzipping...
  Complete!
user1@lancache:~/EpicPrefill$ ./EpicPrefill clear-cache
[10:25:49 AM] Found 3 cached files, totaling 2.61 MiB
[10:25:50 AM] Done!
user1@lancache:~/EpicPrefill$ ./EpicPrefill prefill -f
[10:26:06 AM] Reusing existing auth session...
[10:26:06 AM] Retrieving owned apps
[10:26:10 AM] Loaded new app metadata for 16 apps
[10:26:10 AM] Retrieved 16 apps                                  03.7645

[10:26:10 AM] Starting Satisfactory Early Access
[10:26:10 AM] Downloaded manifest                                00.0498
[10:26:11 AM] Downloading 9.02 GiB
[10:26:11 AM] Detected Lancache server at localhost [127.0.0.1]
[10:26:17 AM] Finished in 06.3728 - 12.15 Gbit/s

[10:26:17 AM] Starting Satisfactory Experimental
[10:26:17 AM] Downloaded manifest                                00.0437
[10:26:17 AM] Downloading 9.02 GiB
[10:26:23 AM] Finished in 05.9489 - 13.02 Gbit/s

ERROR
System.InvalidOperationException: Sequence contains no matching element
  at System.Linq.ThrowHelper.ThrowNoMatchException()
  at System.Linq.Enumerable.First[TSource](IEnumerable`1 , Func`2 )
  at EpicPrefill.EpicGamesManager.DownloadMultipleAppsAsync(Boolean downloadAllOwnedGames, List`1 manualIds)
  at EpicPrefill.CliCommands.PrefillCommand.ExecuteAsync(IConsole console)
  at CliFx.CliApplication.RunAsync(ApplicationSchema applicationSchema, CommandInput commandInput) in /D:\a\CliFx\CliFx\CliFx\CliApplication.cs:147
  at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables) in /D:\a\CliFx\CliFx\CliFx\CliApplication.cs:191
user1@lancache:~/EpicPrefill$

**Comment by Hamsterman** [comment]
I got the same error - but on a fresh install.

**Comment by Hamsterman** [comment]
> I got the same error - but on a fresh install.

Not the same error - I just didn't have any games on the account

**Comment by tpill90** [comment]
> > I got the same error - but on a fresh install.
> 
> Not the same error - I just didn't have any games on the account

Added a check to make sure that at least 1 game is installed as part of this issue https://github.com/tpill90/epic-lancache-prefill/issues/40

**Comment by tpill90** [comment]
@billthecatt I know its been a year since you opened this, but have you seen this pop up since?

**Comment by tpill90** [comment]
Closed since its been over a year since this was opened, and I haven't received any additional info.  Please feel free to reopen if it happens again.

**Comment by slimshizn** [comment]
Seeing this issue now unfortunately when running automatically via cron:

```
System.InvalidOperationException: Sequence contains no matching element
  at void System.Linq.ThrowHelper.ThrowNoMatchException()                       
  at TSource System.Linq.Enumerable.First<TSource>(IEnumerable<TSource> ,       
     Func<TSource, bool> )                                                      
  at async Task EpicPrefill.EpicGamesManager.DownloadMultipleAppsAsync(bool     
     downloadAllOwnedGames, List<string> manualIds)                             
  at async ValueTask EpicPrefill.CliCommands.PrefillCommand.ExecuteAsync(       
     IConsole console)                                                          
  at async ValueTask<int> CliFx.CliApplication.RunAsync(ApplicationSchema       
     applicationSchema, CommandInput commandInput) in CliApplication.cs:148     
  at async ValueTask<int> CliFx.CliApplication.RunAsync(IReadOnlyList<string>   
     commandLineArguments, IReadOnlyDictionary<string, string>                  
     environmentVariables) in CliApplication.cs:190                             
  at async ValueTask<int> CliFx.CliApplication.RunAsync(IReadOnlyList<string>   
     commandLineArguments) in CliApplication.cs:202                             
  at async Task<int> EpicPrefill.Program.Main()                                 
```

Running manually I'm able to bypass that issue it seems.
